{
 "title": "LGL Multisite",
 "time": { "from": "2023-01-23T23:00:00.000Z", "to": "2023-01-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "SELECT DISTINCT(UserName) FROM Users"
   },
   {
    "name": "site",
    "label": "Site",
    "query": "SELECT DISTINCT(SiteName) FROM Sites WHERE UserName  = '${user}'"
   },
   {
    "name": "mach",
    "label": "Machine",
    "query": "SELECT DISTINCT(MachineDescriptor) FROM Machines WHERE UserName  = '${user}' AND SiteName = '${site}'"
   },
   {
    "name": "Feeder1",
    "query": "SELECT DISTINCT ID_feeder\nFROM dati\nINNER JOIN Acquisizioni AS acq ON dati.id_aq =  acq.Id\nINNER JOIN Machines AS mac ON mac.MachineDescriptor = acq.MachineDescriptor\nWHERE mac.MachineDescriptor= '${mach}'"
   },
   {
    "name": "Feeder2",
    "query": "SELECT DISTINCT ID_feeder\nFROM dati\nINNER JOIN Acquisizioni AS acq ON dati.id_aq =  acq.Id\nINNER JOIN Machines AS mac ON mac.MachineDescriptor = acq.MachineDescriptor\nWHERE mac.MachineDescriptor= '${mach}'"
   },
   {
    "name": "param",
    "label": "Parameter",
    "query": "T_des : T_des (dgr), T_read : T_read (dgr), Sm_steps : Sm_steps (steps), Real_speed : Real_speed (rpm), Torque : Torque (mNm), Ftc_out : Ftc_out (mA), Ftc_in : Ftc_in (mA), Meter_cons : Meter_cons (m), Vbus_motor : Vbus_motor (V), T_offset : T_offset (dgr)"
   }
  ]
 },
 "panels": [
  {
   "title": "Feeder Level Comparison:  ${param:value}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  ${param:text} as \"Feeder $Feeder1\"\nFROM Acquisizioni as a\nINNER JOIN dati as d\nON a.Id = d.ID_aq\nWHERE d.ID_feeder = $Feeder1 AND a.MachineDescriptor = \"${mach}\"\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  ${param:text} as \"Feeder $Feeder2\"\r\nFROM Acquisizioni as a\r\nINNER JOIN dati as d\r\nON a.Id = d.ID_aq\r\nWHERE d.ID_feeder = $Feeder2 AND a.MachineDescriptor = \"${mach}\"\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Machine Level On Events",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  on_evts,\n  on_hrs,\n  efficiency,\n  date AS metric\nFROM op_onevts\nWHERE\n  MachineDescriptor = \"$mach\" AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Machine Level Alarm Events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  `Clean Phot`,\n  `ElBrk Open`,\n  `Feeder not found`,\n  `Motor Lock`,\n  `OYB Err`,\n  `PrewindErr`,\n  `SMRangeErr`,\n  `Switch OFF`,\n  `TensmtrErr`,\n  `Yarn Break`,\n  `Other Alarms`,\n  date AS metric\nFROM op_alarmevts\nWHERE\n  MachineDescriptor = \"$mach\" AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}